// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VersionWithRelations } from './version-with-relations';

/**
 * (Schema options: { includeRelations: true })
 * @export
 * @interface CompatibleVersionWithRelations
 */
export interface CompatibleVersionWithRelations {
    /**
     * 
     * @type {number}
     * @memberof CompatibleVersionWithRelations
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CompatibleVersionWithRelations
     */
    versionId?: number;
    /**
     * 
     * @type {number}
     * @memberof CompatibleVersionWithRelations
     */
    otherVersionId?: number;
    /**
     * 
     * @type {VersionWithRelations}
     * @memberof CompatibleVersionWithRelations
     */
    version?: VersionWithRelations;
    /**
     * 
     * @type {VersionWithRelations}
     * @memberof CompatibleVersionWithRelations
     */
    otherVersion?: VersionWithRelations;
}


