// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TechnologiesInclude } from './technologies-include';
import { VersionsFields } from './versions-fields';

/**
 * 
 * @export
 * @interface Filter1
 */
export interface Filter1 {
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof Filter1
     */
    where?: { [key: string]: object; };
    /**
     * 
     * @type {VersionsFields}
     * @memberof Filter1
     */
    fields?: VersionsFields;
    /**
     * 
     * @type {number}
     * @memberof Filter1
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof Filter1
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof Filter1
     */
    skip?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Filter1
     */
    order?: Array<string>;
    /**
     * 
     * @type {Array<TechnologiesInclude>}
     * @memberof Filter1
     */
    include?: Array<TechnologiesInclude>;
}


