// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Technology
 */
export interface Technology {
    /**
     * 
     * @type {number}
     * @memberof Technology
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Technology
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Technology
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Technology
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof Technology
     */
    urlRepository: string;
    /**
     * 
     * @type {string}
     * @memberof Technology
     */
    webSite?: string;
    /**
     * 
     * @type {string}
     * @memberof Technology
     */
    type: TechnologyTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Technology
     */
    environmentTypes?: Array<TechnologyEnvironmentTypesEnum>;
}

/**
    * @export
    * @enum {string}
    */
export enum TechnologyTypeEnum {
    Style = 'style',
    Framework = 'framework',
    Module = 'module',
    Library = 'library'
}
/**
    * @export
    * @enum {string}
    */
export enum TechnologyEnvironmentTypesEnum {
    Frontend = 'frontend',
    Api = 'api',
    Service = 'service',
    Storage = 'storage'
}



