// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TechnologiesFields
 */
export interface TechnologiesFields {
    /**
     * 
     * @type {boolean}
     * @memberof TechnologiesFields
     */
    id?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TechnologiesFields
     */
    name?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TechnologiesFields
     */
    description?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TechnologiesFields
     */
    logo?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TechnologiesFields
     */
    urlRepository?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TechnologiesFields
     */
    webSite?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TechnologiesFields
     */
    type?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TechnologiesFields
     */
    environmentTypes?: boolean;
}


