// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VersionWithRelations } from './version-with-relations';

/**
 * (Schema options: { includeRelations: true })
 * @export
 * @interface TechnologyWithRelations
 */
export interface TechnologyWithRelations {
    /**
     * 
     * @type {number}
     * @memberof TechnologyWithRelations
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TechnologyWithRelations
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TechnologyWithRelations
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof TechnologyWithRelations
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof TechnologyWithRelations
     */
    urlRepository: string;
    /**
     * 
     * @type {string}
     * @memberof TechnologyWithRelations
     */
    webSite?: string;
    /**
     * 
     * @type {string}
     * @memberof TechnologyWithRelations
     */
    type: TechnologyWithRelationsTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof TechnologyWithRelations
     */
    environmentTypes?: Array<TechnologyWithRelationsEnvironmentTypesEnum>;
    /**
     * 
     * @type {Array<VersionWithRelations>}
     * @memberof TechnologyWithRelations
     */
    versions?: Array<VersionWithRelations>;
}

/**
    * @export
    * @enum {string}
    */
export enum TechnologyWithRelationsTypeEnum {
    Style = 'style',
    Framework = 'framework',
    Module = 'module',
    Library = 'library'
}
/**
    * @export
    * @enum {string}
    */
export enum TechnologyWithRelationsEnvironmentTypesEnum {
    Frontend = 'frontend',
    Api = 'api',
    Service = 'service',
    Storage = 'storage'
}



