// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VersionsFields
 */
export interface VersionsFields {
    /**
     * 
     * @type {boolean}
     * @memberof VersionsFields
     */
    id?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VersionsFields
     */
    name?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VersionsFields
     */
    releaseDate?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VersionsFields
     */
    technologyId?: boolean;
}


