// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * (Schema options: { partial: true })
 * @export
 * @interface VersionPartial
 */
export interface VersionPartial {
    /**
     * 
     * @type {number}
     * @memberof VersionPartial
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof VersionPartial
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof VersionPartial
     */
    releaseDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof VersionPartial
     */
    technologyId?: number;
}


