// tslint:disable
/**
 * @scaffoldme-microservices/projects-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.17-alpha.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Entity } from './entity';
import { SelectedTechnology } from './selected-technology';

/**
 * 
 * @export
 * @interface Api
 */
export interface Api {
    /**
     * 
     * @type {string}
     * @memberof Api
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Api
     */
    description?: string;
    /**
     * 
     * @type {SelectedTechnology}
     * @memberof Api
     */
    framework?: SelectedTechnology;
    /**
     * 
     * @type {Array<Entity>}
     * @memberof Api
     */
    entities: Array<Entity>;
    /**
     * 
     * @type {Array<SelectedTechnology>}
     * @memberof Api
     */
    modules: Array<SelectedTechnology>;
}


