// tslint:disable
/**
 * @scaffoldme-microservices/projects-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.17-alpha.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ProjectInfosWithRelations } from './project-infos-with-relations';

/**
 * (Schema options: { includeRelations: true })
 * @export
 * @interface EnvironmentInfosWithRelations
 */
export interface EnvironmentInfosWithRelations {
    /**
     * 
     * @type {number}
     * @memberof EnvironmentInfosWithRelations
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentInfosWithRelations
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentInfosWithRelations
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentInfosWithRelations
     */
    depot?: string;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentInfosWithRelations
     */
    environmentType: EnvironmentInfosWithRelationsEnvironmentTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof EnvironmentInfosWithRelations
     */
    projectInfosId?: number;
    /**
     * 
     * @type {ProjectInfosWithRelations}
     * @memberof EnvironmentInfosWithRelations
     */
    projectInfos?: ProjectInfosWithRelations;
}

/**
    * @export
    * @enum {string}
    */
export enum EnvironmentInfosWithRelationsEnvironmentTypeEnum {
    Frontend = 'frontend',
    Api = 'api',
    Service = 'service',
    Storage = 'storage'
}



