// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Version } from './version';

/**
 * 
 * @export
 * @interface FrontEnd
 */
export interface FrontEnd {
    /**
     * 
     * @type {string}
     * @memberof FrontEnd
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FrontEnd
     */
    description?: string;
    /**
     * 
     * @type {Version}
     * @memberof FrontEnd
     */
    frameworkVersion?: Version;
    /**
     * 
     * @type {Version}
     * @memberof FrontEnd
     */
    styleVersion?: Version;
    /**
     * 
     * @type {Array<Version>}
     * @memberof FrontEnd
     */
    modulesVersions?: Array<Version>;
}


