// tslint:disable
/**
 * @scaffoldme-microservices/projects-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.17-alpha.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SelectedTechnology } from "./selected-technology";

/**
 *
 * @export
 * @interface FrontEnd
 */
export interface FrontEnd {
  /**
   *
   * @type {string}
   * @memberof FrontEnd
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof FrontEnd
   */
  description?: string;
  /**
   *
   * @type {SelectedTechnology}
   * @memberof FrontEnd
   */
  framework: SelectedTechnology;
  /**
   *
   * @type {SelectedTechnology}
   * @memberof FrontEnd
   */
  style?: SelectedTechnology;
  /**
   *
   * @type {Array<SelectedTechnology>}
   * @memberof FrontEnd
   */
  modules?: Array<SelectedTechnology>;
}
