// tslint:disable
/**
 * @scaffoldme-microservices/projects-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.17-alpha.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GroupWithRelations } from './group-with-relations';
import { UserWithRelations } from './user-with-relations';

/**
 * (Schema options: { includeRelations: true })
 * @export
 * @interface GroupUserRoleWithRelations
 */
export interface GroupUserRoleWithRelations {
    /**
     * 
     * @type {number}
     * @memberof GroupUserRoleWithRelations
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupUserRoleWithRelations
     */
    permission: GroupUserRoleWithRelationsPermissionEnum;
    /**
     * 
     * @type {Date}
     * @memberof GroupUserRoleWithRelations
     */
    expirationDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GroupUserRoleWithRelations
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GroupUserRoleWithRelations
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof GroupUserRoleWithRelations
     */
    groupId?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupUserRoleWithRelations
     */
    userId?: string;
    /**
     * 
     * @type {GroupWithRelations}
     * @memberof GroupUserRoleWithRelations
     */
    group?: GroupWithRelations;
    /**
     * 
     * @type {UserWithRelations}
     * @memberof GroupUserRoleWithRelations
     */
    user?: UserWithRelations;
}

/**
    * @export
    * @enum {string}
    */
export enum GroupUserRoleWithRelationsPermissionEnum {
    Owner = 'Owner',
    Developer = 'Developer',
    Guest = 'Guest',
    Reporter = 'Reporter'
}



