// tslint:disable
/**
 * @scaffoldme-microservices/projects-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.17-alpha.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * (Schema options: { title: \'NewProjectInfos\', exclude: [ \'id\' ] })
 * @export
 * @interface NewProjectInfos
 */
export interface NewProjectInfos {
    /**
     * 
     * @type {string}
     * @memberof NewProjectInfos
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewProjectInfos
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof NewProjectInfos
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof NewProjectInfos
     */
    ownerId?: string;
    /**
     * 
     * @type {number}
     * @memberof NewProjectInfos
     */
    groupId?: number;
}


