// tslint:disable
/**
 * @scaffoldme-microservices/projects-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.17-alpha.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EnvironmentInfosWithRelations } from './environment-infos-with-relations';
import { GroupWithRelations } from './group-with-relations';
import { UserWithRelations } from './user-with-relations';

/**
 * (Schema options: { includeRelations: true })
 * @export
 * @interface ProjectInfosWithRelations
 */
export interface ProjectInfosWithRelations {
    /**
     * 
     * @type {number}
     * @memberof ProjectInfosWithRelations
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectInfosWithRelations
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectInfosWithRelations
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectInfosWithRelations
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectInfosWithRelations
     */
    ownerId?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectInfosWithRelations
     */
    groupId?: number;
    /**
     * 
     * @type {Array<EnvironmentInfosWithRelations>}
     * @memberof ProjectInfosWithRelations
     */
    environmentsInfos?: Array<EnvironmentInfosWithRelations>;
    /**
     * 
     * @type {UserWithRelations}
     * @memberof ProjectInfosWithRelations
     */
    owner?: UserWithRelations;
    /**
     * 
     * @type {GroupWithRelations}
     * @memberof ProjectInfosWithRelations
     */
    group?: GroupWithRelations;
}


