// tslint:disable
/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Relation
 */
export interface Relation {
    /**
     * 
     * @type {number}
     * @memberof Relation
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Relation
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Relation
     */
    foreignKey: string;
    /**
     * 
     * @type {string}
     * @memberof Relation
     */
    primaryKey: string;
    /**
     * 
     * @type {string}
     * @memberof Relation
     */
    type: RelationTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum RelationTypeEnum {
    HasOne = 'hasOne',
    HasMany = 'hasMany',
    BelongsTo = 'belongsTo'
}



